### ISSUE TITLE
ConnectionType does not support 'Satellite' option

### ISSUE THREAD

**Issue by astsiatsko** [maxmind/minfraud-api-java#288]
Due to some circumstances, we cannot migrate our project to java 11 yet, so we had to use library 1.18.0
In this library we got an issue that class 

`com.maxmind.geoip2.model.ConnectionTypeResponse.ConnectionType `
enum does not contain 'Satellite' enum. And because of it we have income losses. Can you please explain is there version for java 8 which has no bugs and totally consistent with the latest API logic? Thanks

**Comment by oschwald** [comment]
Unfortunately, we no longer providing updates to 1.* and the 2.* releases do not support Java 8. The issue you are running into is due to the newly added `/ip_address/traits/connection_type` value. Older versions of the client only support this value as the same model was used by the GeoIP2 Enterprise database, which also has the field. Unfortunately, as deserializing from JSON was not the intended use case when the field was added, older versions of the library do not correctly handle unknown values.

Beyond upgrading to Java 11 and a newer release, you might be able to downgrade the `geoip2` dependency to `2.6.0`, which is before the GeoIP2 Enterprise support was added. I am not entirely sure if this will work without also downgrading your version of this library.

You may also reach out to support@maxmind.com for additional help.

**Comment by astsiatsko** [comment]
Thanks, where can I read that you do not support these releases? Why these releases are still in github and not marked as do not support?

**Comment by oschwald** [comment]
We have all historical releases on GitHub, as is the norm for most projects. I would suggest reaching out to support@maxmind.com for more assistance.

**Comment by astsiatsko** [comment]
Sorry but your legacy library (aka 2015) still works as expected, but your library from 2021 is marked as historical? It does not make sense, all versions, even historical ones, should be operational or marked as do not support. Millions of businesses still use java 8 an should get bug free library. Thanks

**Comment by oschwald** [comment]
We have released `geoip2`[ 2.17.0](https://github.com/maxmind/GeoIP2-java/releases/tag/v2.17.0) and [`minfraud` 1.19.0](https://github.com/maxmind/minfraud-api-java/releases/tag/v1.19.0) for users who cannot upgrade from Java 8. Please note that these will likely be the last releases with Java 8 support.
